### ISSUE TITLE
利用規約・プライバシーポリシーを作成する

### ISSUE THREAD

**Issue by tkgshn** [dig-dao/simplegrants#10]
以下、利用規約を作るために必要になりそうな要素を下書きとして列挙する
- **サービスの内容**: 「このDigDAOマッチングドネーション」プロジェクトは、DigDAOを中心とし、公益プロジェクトに対する新しい資金分配の形を模索するために運営する。そのため、本プラットフォームに公益プロジェクトを列挙し、支持者から寄付を募るクラウドファンディングツールを運営する
- **ユーザーに守って欲しいルール**:  https://scrapbox.io/public-goods-funding/%E5%85%AC%E7%9B%8A%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%A8%E3%81%97%E3%81%A6%E6%8E%B2%E8%BC%89%E3%81%97%E3%81%9F%E3%81%84%E4%BA%BA%E3%81%B8#66319e0209c5f2000085ef3a
    - （寄付者として）一人が複数アカウントを作って寄付するのは絶対にやめてほしい（疑わしい場合があれば調査する、場合によっては寄付を無効とする場合もある）
    - （プロジェクト側として）なりすましや、見返り・賄賂を渡して投票を得ようとする行為は絶対にやめて欲しい
- **ユーザーがルールに違反した場合は運営としてどのように対処するか**: 悪質だと判断した場合、寄付の取り消しや、プロジェクト掲載の取消などを行う場合がある。その場合、返金の対応ができないこともあり得る。
- **自社で責任を持てること**: QFの計算や寄付周りの設計などは万全を期して設計しているが、やむを得ず本プロジェクト自体が中止になることはある。その場合は、Stripeの手数料を引いた金額を返金する。時間はかかるかもしれないが、QFがうまくいった場合はきちんとプロジェクト側に資金を分配する。
- **責任を持てないこと**: もしかしたら、QFの仕組みが途中でバグっているかもしれない。本プロジェクトが何かしらの理由で中止になるかもしれない。
- **データについて**: この実験をやる上で得られる寄付データは、今後のプロジェクト体験の向上や、各プロジェクトのマーケティングや文章のアドバイスなどに使うことがある。そのほか、寄付データは終了後レポートという形で公開する。ただし、誰がどこに寄付したかという情報についてはメールアドレスやGoogleアカウントに紐づけられている名前含めて、一般には開示しない。Cookieに関しては、Authかなんかで必須な分のみ取得する。

**Comment by halsk** [comment]
@tkgshn 
弁護士との相談結果

https://scrapbox.io/public-goods-funding/%E3%83%9E%E3%83%83%E3%83%81%E3%83%B3%E3%82%B0%E3%83%89%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%AE%E5%BC%81%E8%AD%B7%E5%A3%AB%E8%A6%8B%E8%A7%A3

1点こちらで検討したいこととして、これがある。

> 自社で責任を持てること: QFの計算や寄付周りの設計などは万全を期して設計しているが、やむを得ず本プロジェクト自体が中止になることはある。その場合は、Stripeの手数料を引いた金額を返金する。時間はかかるかもしれないが、QFがうまくいった場合はきちんとプロジェクト側に資金を分配する。

私としては、ここまで責任は持ちたくない。リストに掲載する前に変なプロジェクトは弾いたうえで、寄付先がまともかどうかは寄付者が判断する建付けにしたい。つまり、支払うところまでがサイトの責任。
そうでないと、プロジェクトが完了するまで支払いができない。→ トラッキングする必要が出てきて、事務処理の負担になる
こちらとしては、QFのラウンドが終わった時点で速やかに支払い処理をしてしまいたい。

**Comment by tkgshn** [comment]
Scrapbox上で返信しました。 @hal
