### ISSUE TITLE
プロジェクトの新規登録biGoogleSpreadシートとGASでできるようにする。

### ISSUE THREAD

**Issue by yu23ki14** [dig-dao/simplegrants#3]
# 背景

バックエンドのエンドポイントとして新規プロジェクト登録は存在するが、それをたたくためのフロントエンドのインターフェースがない。curlでたたけばいいが面倒くさい。

# What

プロジェクトの新規登録をGAS経由でしたい。
ユーザーストーリー
1. 申請者がGoogleFormから応募
2. 運営がチェックして、OKになったらListのフラグを立てる
3. GASでスプシのデータをエンドポイント経由で登録

\*更新はDB直接でいったんよい

**Comment by tkgshn** [comment]
このissueは閉じて、 #20 の方法を使うことに決定
