### ISSUE TITLE
ログインユーザーの過去の寄付履歴がみれるようにする

### ISSUE THREAD

**Issue by yu23ki14** [dig-dao/simplegrants#4]
# What

マイページは存在するが、そこに過去寄付した履歴データがでてこないので、それを表示させる

**Comment by tkgshn** [comment]
`review.tsx`にこの辺りのコードがある。

用語整理
- donation: これはmatching poolに寄付することを指すっぽい
- pool: matching poolのこと
- contribution: プロジェクトへの寄付のこと。実質、支援みたいな感じっぽい。


<img width="1230" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/d414a581-85c6-408a-b253-715f480bd6c8">

<img width="1227" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/780d6cbb-5c6c-4931-8086-de464a6f94a7">

<img width="1220" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/abc054a9-d4a0-4ce4-8578-2c5bdb84fc7b">


もしかしたら私の翻訳が間違っているのかもしれないが、「寄付したもの」を見るページは存在しないかもしれない？このプロフィール機能は、どちらかというとプロジェクトオーナー向けなのかもしれない。

**Comment by tkgshn** [comment]
ただ、それと同時に「寄付の額」も表示されていない。
寄付したものがDBに反映されているかは要確認である。

**Comment by tkgshn** [comment]
<img width="1425" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/afd9be54-1323-4087-af62-5dfcd0ee4b37">
DBに突っ込んだらいけたけど、寄付行動とは紐づいてない

**Comment by tkgshn** [comment]
どのコミットか忘れたけど、これもできるようになりました。contributionのtableに入っているかが原因でした。
