### ISSUE TITLE
Bastionのあり方を考える

### ISSUE THREAD

**Issue by ushios** [dig-dao/simplegrants#45]
踏み台サーバーをDBに触りに行くようで作ってるように見受けられるが
https://github.com/dig-dao/simplegrants/blob/main/cdk/lib/vpc-stack.ts#L62-L77
https://github.com/dig-dao/simplegrants/blob/main/cdk/lib/rds-stack.ts#L35-L39

`anyIpv4`でssh全開だと良くないので、ポート全部閉じて[ssmを使用する](https://docs.aws.amazon.com/ja_jp/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html)か、DBへのアクセスは諦めてsnapshotからデバッグするか、IP制限を行い、sshのポートを22番以外にするといいと思っています。

https://github.com/dig-dao/simplegrants/blob/main/cdk/lib/vpc-stack.ts#L56-L60

**Comment by yu23ki14** [comment]
@ushios 
以下の対応をSecurityGroup更新することで対応しました。Allow IP Addressesは環境変数で管理
- ポートを22から変更
- IP制限をかける

https://github.com/dig-dao/simplegrants/blob/922b4efc76908002def1929c10b86d428035882e/cdk/lib/vpc-stack.ts#L56
