### ISSUE TITLE
WIP: UIでいらないものを隠す

### ISSUE THREAD

**Issue by yu23ki14** [dig-dao/simplegrants#5]
隠すものの詳細は後程

**Comment by tkgshn** [comment]
隠すもの: 
- 「プロジェクト登録」ボタン
- 現在2つのボタン（サインイン・ログインボタン）があるけど、動きはアカウント作成→プロジェクト一覧と同じなので全部"プロジェクトを見る"とかでいいと思う。
- プロジェクト登録画面
- プロフィールページで表示される「資金プールへの寄付」「作成したプロジェクト」「作成した資金プール」「受け取った額」など 
    - ref: https://github.com/dig-dao/simplegrants/issues/4#issuecomment-2046330547
-

**Comment by tkgshn** [comment]
「プロジェクト登録」の画面は、 #20 で話した通りに"寄付する人から見えなくていいけど、運営はフロントのUIから入力する"のでボタンを消すだけでページは削除しないでほしい @yu23ki14

**Comment by tkgshn** [comment]
#26 ができるようになったので着手します

**Comment by tkgshn** [comment]
- [ ] サインイン・ログインの2つのボタンはいらないのでどっちか削除する
- [ ] 「公益プロジェクを見る」クリックの後、プロジェクト一覧へ遷移させる

**Comment by tkgshn** [comment]
残るは #10 のみなのでクローズします。
