### ISSUE TITLE
ハードコーディングでの日本語ローカライゼーション（言語・通貨含む）

### ISSUE THREAD

**Issue by yu23ki14** [dig-dao/simplegrants#6]

**Comment by tkgshn** [comment]
これ、通貨周りもする必要があることに気がついたのでreopenします

**Comment by tkgshn** [comment]
## 課題詳細
1. プロジェクトの一覧表示の際に$表記になる
    - <img width="1344" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/5088c370-455d-43de-b809-f3b2ed26b379">
2. プロジェクトの詳細画面で目標金額・受取済み金額が$になる
    - <img width="1353" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/b9a7998c-2b59-4049-9276-567c4a24b813">
3. カートボタンを押すとUSD表示になる
    - <img width="391" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/7b87c41b-4036-4e8b-81fa-21b6c6c345aa">
4. カート内プロジェクト表示の際にUSDになる
    - <img width="1358" alt="image" src="https://github.com/dig-dao/simplegrants/assets/45249410/2cea7ceb-6d1c-4a7e-aae3-929aed36bf16">
5. サイト内ではUSD表示なのに、stripeに移ると日本円になる
    - [![Image from Gyazo](https://i.gyazo.com/0e03d361d1171d1872fd55a1c62f42b8.gif)](https://gyazo.com/0e03d361d1171d1872fd55a1c62f42b8)
